# Builder Image
FROM golang:1.15-alpine as builderGolang

# Setting the working directory and copying the files
WORKDIR /usr/src/app
COPY src .

RUN go build -ldflags="-s -w" -v -o challenge01-go main.go

# Running builder
FROM scratch
WORKDIR /usr/src/app

COPY --from=builderGolang /usr/src/app .

CMD ["./challenge01-go"]